name: Code Style

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: composer install

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes

  prettier-eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Prettier and Eslint
        run: npm run prettier && npm run eslint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier and Eslint changes
          branch: ${{ github.head_ref }}
